services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./unicats.sdp:/config/unicats.sdp:ro
